version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests          
          command: pytest
      -run:
          name: Compile code
          command: run.py      

workflows:
  webpage: 
    jobs:
      - build-and-test:
         filters:
            branches:
              only:
                - main